--2023 MoM SUMMARY
SELECT
   date_trunc('MONTH', TRANSACTION_DATE) as TRANSACTION_MONTH
  ,sum(AMOUNT) as TOTAL_AMOUNT
  ,concat(to_varchar(round((sum(AMOUNT)/LAG(sum(AMOUNT)) OVER (ORDER BY date_trunc('MONTH', TRANSACTION_DATE)))-1,2)*100),'%') AS MOM
FROM LENDINGONE_DW.PUBLIC.CONSOLIDATED_DATASET
WHERE EXTRACT(YEAR FROM TRANSACTION_DATE) = '2023'
GROUP BY 
    TRANSACTION_MONTH
ORDER BY 
    TRANSACTION_MONTH;

--2023 TOP FIVE CUSTOMERS BY TOTAL SPENT
SELECT
    customer_id,
    customer_name,
    email,
    SUM(amount) AS total_spent
FROM LENDINGONE_DW.PUBLIC.CONSOLIDATED_DATASET
WHERE EXTRACT(YEAR FROM TRANSACTION_DATE) = '2023'
GROUP BY
    customer_id,
    customer_name,
    email
ORDER BY
    total_spent DESC
LIMIT 5;

--2023 TOP CUSTOMERS BY TRANSACTION FREQUENCY
SELECT
    customer_id,
    customer_name,
    email,
    COUNT(transaction_id) AS transaction_count
FROM
    LENDINGONE_DW.PUBLIC.CONSOLIDATED_DATASET
    EXTRACT(YEAR FROM TRANSACTION_DATE) = '2023'
GROUP BY
    customer_id,
    customer_name,
    email
ORDER BY
    transaction_count DESC;
    
--2023 YEAR SUMMARY
SELECT
   date_trunc('YEAR', TRANSACTION_DATE) as TRANSACTION_YEAR
  ,count(*) as TOTAL_TRANSACTIONS
  ,sum(AMOUNT) as TOTAL_AMOUNT
  ,round(sum(AMOUNT)/count(*),2) AVERAGE_TRANSACTION_AMOUNT
  ,round(avg(AMOUNT),0) AVG_AMOUNT
  ,min(AMOUNT) MIN_AMOUNT
  ,max(AMOUNT) MAX_AMOUNT
FROM LENDINGONE_DW.PUBLIC.CONSOLIDATED_DATASET
WHERE EXTRACT(YEAR FROM TRANSACTION_DATE) = '2023'
GROUP BY 
    TRANSACTION_YEAR
ORDER BY 
    TRANSACTION_YEAR;